### PR TITLE
Update to Rails 4.2

### PR DESCRIPTION
**Pull request by yurifrl**

### CODE REVIEW

**Comment by futhr** [comment]
Hi @yurifrl, it seems correct, just not sure about passing `email` instead of `id` ? Can you elaborate this change please (also build fails).

**Comment by yurifrl** [comment]
I agree, not cool to pass email.
In wich version of spree is Travis testing? the master branch of spree's test mailer, requires a email i guess, https://github.com/spree/spree/blob/master/core/app/mailers/spree/test_mailer.rb

**Comment by futhr** [comment]
They made some weird change to Travis CI so it is no longer possible to select branch when generating the badge (branch dropdown always blank), maybe a bug that should be reported. I try to stick to the old badge style link that sets branch by querystring an hope it apply. So in short it should test correct branch for each commit.

**Comment by futhr** [comment]
The `master` branch still use Rails v4.1.9 in test mode and Rails does not have `ActiveJob` until 4.2.0. I tried to apply a similar update for `spree_email_to_friend` gem's `master`branch without any luck before checking if it was supported.

**Comment by futhr** [comment]
@yurifrl I have now cherry-picked 78c53fc into `master` branch. If you want you can git rebase and squash the other changes and have it as a pending PR until we on Rails v4.2.x.

**Comment by futhr** [comment]
@yurifrl `master` branch has now been updated using Spree v3.1.0.stable that's for Rails 4.2 so your last commit has been merged, thanks.

**Comment by yurifrl** [comment]
Thank you @futhr

**Comment by futhr** [comment]
You was correct @yurifrl about the change from `id` to `email` as noted in #8 so I will apply that commit to for `2-4-stable` and `master` branch.

**Comment by yurifrl** [comment]
I guess this is because active job

**Pull request closed without merging**
