### PR TITLE
Modify specs for mail_settings and mail_methods...

### LINKED ISSUE #13: Test emails works great but the real ones not
Hello!
I'm trying to use spree_mail_settings in my spree instance but i have one major problem with that - the test email is working as it should but the actual mails sent by the app during checkout/payment/shipment process are being sent properly. There are no any errors nor warnings, console log says that email has been sent but it's not (i can say that for 100% because it is not present in Mandrill's outbound page while the test ones are there).

I'm on master branch of spree and spree_mail_settings

Thanks in advance.

### PR DESCRIPTION
**Pull request by aishmita-aggarwal**
Allow application configuration for delivery method to not be overriden fixes issue #19...
Modify interceptor to use mails_from config setting fixes #13...
Add default value for smtp_username and smtp_password...
Modify smtp_password clear check when smtp_username is blank...
Add Devise helper to spec_helper configuration for spec fix
Bump version to 3.1.0.beta..
Upgrade versions for rspec-rails to 3.4.0 and sass-rails to 5.0.0

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Hi @aishmita-aggarwal  could you break this one to several commits so it's more readable? Thaaaaaanks :)

**Comment by aishmita-aggarwal** [comment]
@damianlegawiec Done as suggested. Please check :)

**Comment by aishmita-aggarwal** [comment]
@mafi88 But if I would like to clear smtp_password, I wont be able to because of that.
According to #2094, yes it would break it. About #2094, shouldn't we restrict it to staging/developments as suggested?

**Comment by Mafi88** [comment]
@aishmita-aggarwal I think we should :)

**Comment by aishmita-aggarwal** [comment]
Thank you, @Mafi88. Thoughts @priyank-gupta , @damianlegawiec ?

**Comment by aishmita-aggarwal** [comment]
Actually, I can't replicate the issue #2094 on master or 3-0-stable. So I think we need not re add the code for skipping smtp_password when left blank in the form.

**Pull request merged**
