### PR TITLE
to use Spree.admin_path

### PR DESCRIPTION
**Pull request by odk211**
https://github.com/spree/spree/blob/master/guides/content/release_notes/3_1_0.md#noteworthy-changes-1

### CODE REVIEW

**Comment by odk211** [comment]
@damianlegawiec It is necessary for spree-3.1.0 I think.

**Comment by damianlegawiec** [comment]
@odk211 - you're correct :) could you look at the specs? they are failing currently :(

**Comment by odk211** [comment]
Test passed, after rebase :)
and I added some files to .gitignore, is it OK?

**Comment by damianlegawiec** [comment]
Thanks again @odk211 👍

**Pull request merged**
